packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  "@swc/core": true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - "@swc/core"

overrides:
  "@expo/dom-webview": "56.0.5"
  "@types/react": "19.2.17"
  "@types/react-dom": "19.2.3"

patchedDependencies:
  react-native-css-interop@0.2.6: patches/react-native-css-interop@0.2.6.patch

peerDependencyRules:
  ignoreMissing:
    - "@expo/dom-webview"
  allowAny:
    - "@expo/dom-webview"
